# Database Config
spring.application.name=ShopGiayOnline
server.port=8080

spring.datasource.url=jdbc:postgresql://aws-0-ap-southeast-1.pooler.supabase.com:6543/postgres?sslmode=require&pgbouncer=true&pool_mode=session
spring.datasource.username=postgres.zlhvmzwwxhefyibefqqb
spring.datasource.password=shopgiayonlinedb
spring.datasource.driver-class-name=org.postgresql.Driver

# Hikari pool (tùy chỉnh cho Transaction Pooler)
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=30000
spring.datasource.hikari.leak-detection-threshold=60000

# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.tool.hbm2ddl=TRACE
logging.level.com.zaxxer.hikari=DEBUG

# Mail Config
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=shopgiayxinchao@gmail.com
spring.mail.password=bvmp xmks qxdr twtb
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.debug=true

#JWT
app.jwt-secret=846bce31ab3e1d5f277de82feb5fbe717a070eba001c8fee0e6ea81ba18de39e
app-jwt-expiration-milliseconds=604800000

frontend.base-endpoint=http://127.0.0.1:5173
